# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
