# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20171121_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='Tytuł')),
                ('time', models.CharField(max_length=128, verbose_name='Czas')),
                ('date', models.CharField(max_length=128, verbose_name='Data')),
            ],
        ),
    ]
