# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_shows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shows',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa'),
        ),
    ]
